DATALOADER:
  batch_size: 48
  num_workers: 0
EXP:
  DATASET: modelnet40_dgcnn
  EXP_ID: dgcnn_robustnet_run_1
  LOSS_NAME: smooth
  MODEL_NAME: robustnet
  SEED: 1
  TASK: cls
  # OPTIMIZER: pct
TRAIN:
  l2: 1e-4
  learning_rate: 0.0001
