DATALOADER:
  batch_size: 12
  num_workers: 0
EXP:
  DATASET: modelnet40_c
  EXP_ID: c_gdanet_run_1
  LOSS_NAME: smooth
  METRIC: acc
  MODEL_NAME: gdanet
  SEED: 1
  TASK: cls
TRAIN:
  l2: 1e-4
ADAPT:
  METHOD: tent
  ITER: 10
